unit eiConstants;

interface

uses
  eiTypes;

const
  SHORT_SIZE = sizeof(short);
  EASYIP_PORT = 995;
  //
  EASYIP_HEADERSIZE = 20;
  EASYIP_DATASIZE = 256;
  //
  EASYIP_FLAG_INFO = $01;
  EASYIP_FLAG_BIT_OR = $02;
  EASYIP_FLAG_BIT_AND = $04;
  EASYIP_FLAG_NOACK = $40;
  EASYIP_FLAG_RESPONSE = $80;
  //
  EASYIP_ERROR_OPERAND = $01;
  EASYIP_ERROR_OFFSET = $02;
  EASYIP_ERROR_DATASIZE = $04;
  EASYIP_ERROR_NOSUPPORT = $10;
  //
  EASYIP_TYPE_FLAGWORD = 1;
  EASYIP_TYPE_INPUTWORD = 2;
  EASYIP_TYPE_OUTPUTWORD = 3;
  EASYIP_TYPE_REGISTER = 4;
  EASYIP_TYPE_TIMER = 5;
  EASYIP_TYPE_STRING = 11;

  CHANNEL_DEFAULT_TIMEOUT = 2000;
  
  WINSOCK_VERSION = $0202;
  LANG_ID = $400;

resourcestring
  DEBUG_MESSAGE_DESTROY = '%s is destroyed';
  DEBUG_MESSAGE_CREATE = '%s is created';

implementation

end.

